"""Constants for the Petlibro Local integration."""

DOMAIN = "petlibro_local"

# MQTT
DEVICE_PRODUCT_ID = "PLAF203"
SUPPORTED_PRODUCT_IDS = ["PLAF203", "PLAF203S", "PLAF301"]
MQTT_PORT = 1883

# MQTT topic templates
TOPIC_BASE = "dl/{product_id}/{serial}/device"
TOPIC_HEART_POST = TOPIC_BASE + "/heart/post"
TOPIC_NTP_POST = TOPIC_BASE + "/ntp/post"
TOPIC_NTP_SUB = TOPIC_BASE + "/ntp/sub"
TOPIC_OTA_POST = TOPIC_BASE + "/ota/post"
TOPIC_OTA_SUB = TOPIC_BASE + "/ota/sub"
TOPIC_CONFIG_POST = TOPIC_BASE + "/config/post"
TOPIC_CONFIG_SUB = TOPIC_BASE + "/config/sub"
TOPIC_EVENT_POST = TOPIC_BASE + "/event/post"
TOPIC_EVENT_SUB = TOPIC_BASE + "/event/sub"
TOPIC_SERVICE_POST = TOPIC_BASE + "/service/post"
TOPIC_SERVICE_SUB = TOPIC_BASE + "/service/sub"
TOPIC_SYSTEM_POST = TOPIC_BASE + "/system/post"
TOPIC_SYSTEM_SUB = TOPIC_BASE + "/system/sub"
TOPIC_BROADCAST_SUB = TOPIC_BASE + "/broadcast/sub"

# Config entry keys
CONF_SERIAL = "serial"
CONF_PRODUCT_ID = "product_id"
CONF_MQTT_USERNAME = "mqtt_username"
CONF_MQTT_PASSWORD = "mqtt_password"
CONF_FEEDING_PLANS = "feeding_plans"

# Timing
HEARTBEAT_WATCHDOG_SEC = 81
HEARTBEAT_INTERVAL_SEC = 30
NTP_DRIFT_THRESHOLD_SEC = 10
DEVICE_INIT_WATCHDOG_SEC = 10

# Feeding plans
MAX_FEEDING_PLANS = 9

# Commands (cmd field values)
CMD_HEARTBEAT = "HEARTBEAT"
CMD_NTP = "NTP"
CMD_NTP_SYNC = "NTP_SYNC"
CMD_OTA_INFORM = "OTA_INFORM"
CMD_OTA_PROGRESS = "OTA_PROGRESS"
CMD_OTA_UPGRADE = "OTA_UPGRADE"
CMD_GET_CONFIG = "GET_CONFIG"
CMD_SERVER_CONFIG_PUSH = "SERVER_CONFIG_PUSH"
CMD_ATTR_GET_SERVICE = "ATTR_GET_SERVICE"
CMD_ATTR_SET_SERVICE = "ATTR_SET_SERVICE"
CMD_ATTR_PUSH_EVENT = "ATTR_PUSH_EVENT"
CMD_DEVICE_START_EVENT = "DEVICE_START_EVENT"
CMD_ERROR_EVENT = "ERROR_EVENT"
CMD_GRAIN_OUTPUT_EVENT = "GRAIN_OUTPUT_EVENT"
CMD_GET_FEEDING_PLAN_EVENT = "GET_FEEDING_PLAN_EVENT"
CMD_FEEDING_PLAN_SERVICE = "FEEDING_PLAN_SERVICE"
CMD_MANUAL_FEEDING_SERVICE = "MANUAL_FEEDING_SERVICE"
CMD_DEVICE_REBOOT = "DEVICE_REBOOT"
CMD_RESTORE = "RESTORE"
CMD_RESET = "RESET"
CMD_BINDING = "BINDING"
CMD_UNBIND = "UNBIND"
CMD_DEVICE_INFO_SERVICE = "DEVICE_INFO_SERVICE"
CMD_DEVICE_PROPERTIES_SERVICE = "DEVICE_PROPERTIES_SERVICE"
CMD_INITIALIZE_SD_CARD_SERVICE = "INITIALIZE_SD_CARD_SERVICE"
CMD_WIFI_RECONNECT_SERVICE = "WIFI_RECONNECT_SERVICE"
CMD_WIFI_CHANGE_SERVICE = "WIFI_CHANGE_SERVICE"
CMD_TUTK_CONTRACT_SERVICE = "TUTK_CONTRACT_SERVICE"
CMD_DETECTION_EVENT = "DETECTION_EVENT"
CMD_DEVICE_DATA_EVENT = "DEVICE_DATA_EVENT"
CMD_PET_IDENTIFY_EVENT = "PET_IDENTIFY_EVENT"
CMD_WAREHOUSE_DOOR_EVENT = "WAREHOUSE_DOOR_EVENT"

# Code response values
CODE_OK = 0
CODE_ERROR_DEVICE_NOT_BOUND = 2030

# Entity platforms
PLATFORMS = [
    "sensor",
    "binary_sensor",
    "switch",
    "button",
    "number",
    "select",
    "event",
]
